services:
  auth-db:
    image: postgres:16-alpine
    env_file:
      - ./auth-service/db.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./auth-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  auth-api:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - auth-db
    ports:
      - "3001:3001"

  api-gateway-api:
    build: ./api-gateway
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-api
    ports:
      - 8000:8000

volumes:
 auth_db_data: